version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Packaging application..."
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests
  post_build:
    commands:
      - echo "Build successful. Preparing for deployment..."
      # Zip the target folder AND the Dockerfile
      - zip -r deploy.zip target/*.jar Dockerfile

      - aws s3 cp deploy.zip s3://$ARTIFACT_BUCKET/deploy.zip

      - |
        
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$TARGET_INSTANCE_NAME" "Name=instance-state-name,Values=running" --query "Reservations[].Instances[].InstanceId" --output text | awk '{print $1}')
        
        if [ "$INSTANCE_ID" == "None" ] || [ -z "$INSTANCE_ID" ]; then
          echo "Error: No running instance found for $TARGET_INSTANCE_NAME"
          exit 1
        fi

        echo "Deploying to Instance: $INSTANCE_ID"

        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters "commands=[
            'mkdir -p /app',
            'aws s3 cp s3://$ARTIFACT_BUCKET/deploy.zip /app/deploy.zip',
            'cd /app && unzip -o deploy.zip',
            'docker build -t magic-app .',
            'docker stop magic-app || true',
            'docker rm magic-app || true',
            'docker run -d --name magic-app -p 8085:8085 magic-app'
          ]" \
          --region "$AWS_REGION_NAME"
